// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: redeem_code/redeem_code.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRedeemCodeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UsageLimit    int32                  `protobuf:"varint,3,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatorId     int64                  `protobuf:"varint,8,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName   string                 `protobuf:"bytes,9,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRedeemCodeBatchRequest) Reset() {
	*x = CreateRedeemCodeBatchRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRedeemCodeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedeemCodeBatchRequest) ProtoMessage() {}

func (x *CreateRedeemCodeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedeemCodeBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateRedeemCodeBatchRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRedeemCodeBatchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRedeemCodeBatchRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRedeemCodeBatchRequest) GetUsageLimit() int32 {
	if x != nil {
		return x.UsageLimit
	}
	return 0
}

func (x *CreateRedeemCodeBatchRequest) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CreateRedeemCodeBatchRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CreateRedeemCodeBatchRequest) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *CreateRedeemCodeBatchRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateRedeemCodeBatchRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateRedeemCodeBatchRequest) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

type RedeemCodeBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UsageLimit    int32                  `protobuf:"varint,4,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	TotalCount    int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UsedCount     int32                  `protobuf:"varint,6,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatorId     int64                  `protobuf:"varint,10,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName   string                 `protobuf:"bytes,11,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemCodeBatchResponse) Reset() {
	*x = RedeemCodeBatchResponse{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCodeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCodeBatchResponse) ProtoMessage() {}

func (x *RedeemCodeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCodeBatchResponse.ProtoReflect.Descriptor instead.
func (*RedeemCodeBatchResponse) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{1}
}

func (x *RedeemCodeBatchResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RedeemCodeBatchResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RedeemCodeBatchResponse) GetUsageLimit() int32 {
	if x != nil {
		return x.UsageLimit
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RedeemCodeBatchResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *RedeemCodeBatchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *RedeemCodeBatchResponse) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *RedeemCodeBatchResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RedeemCodeBatchResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{2}
}

func (x *IDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{3}
}

func (x *GetListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRedeemCodeBatchListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Page          int32                      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                      `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*RedeemCodeBatchResponse `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedeemCodeBatchListResponse) Reset() {
	*x = GetRedeemCodeBatchListResponse{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedeemCodeBatchListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedeemCodeBatchListResponse) ProtoMessage() {}

func (x *GetRedeemCodeBatchListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedeemCodeBatchListResponse.ProtoReflect.Descriptor instead.
func (*GetRedeemCodeBatchListResponse) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{4}
}

func (x *GetRedeemCodeBatchListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRedeemCodeBatchListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRedeemCodeBatchListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRedeemCodeBatchListResponse) GetData() []*RedeemCodeBatchResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRedeemCodeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRedeemCodeBatchRequest) Reset() {
	*x = UpdateRedeemCodeBatchRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRedeemCodeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRedeemCodeBatchRequest) ProtoMessage() {}

func (x *UpdateRedeemCodeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRedeemCodeBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateRedeemCodeBatchRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRedeemCodeBatchRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRedeemCodeBatchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRedeemCodeBatchRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRedeemCodeBatchRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *UpdateRedeemCodeBatchRequest) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *UpdateRedeemCodeBatchRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RedeemCodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RedeemCodeBatchId int64                  `protobuf:"varint,2,opt,name=redeem_code_batch_id,json=redeemCodeBatchId,proto3" json:"redeem_code_batch_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value             string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	UsageLimit        int32                  `protobuf:"varint,5,opt,name=usage_limit,json=usageLimit,proto3" json:"usage_limit,omitempty"`
	UsedCount         int32                  `protobuf:"varint,6,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	ExpirationAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiration_at,json=expirationAt,proto3" json:"expiration_at,omitempty"`
	IsDel             int32                  `protobuf:"varint,8,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RedeemCodeResponse) Reset() {
	*x = RedeemCodeResponse{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemCodeResponse) ProtoMessage() {}

func (x *RedeemCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemCodeResponse.ProtoReflect.Descriptor instead.
func (*RedeemCodeResponse) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{6}
}

func (x *RedeemCodeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RedeemCodeResponse) GetRedeemCodeBatchId() int64 {
	if x != nil {
		return x.RedeemCodeBatchId
	}
	return 0
}

func (x *RedeemCodeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RedeemCodeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RedeemCodeResponse) GetUsageLimit() int32 {
	if x != nil {
		return x.UsageLimit
	}
	return 0
}

func (x *RedeemCodeResponse) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *RedeemCodeResponse) GetExpirationAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationAt
	}
	return nil
}

func (x *RedeemCodeResponse) GetIsDel() int32 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *RedeemCodeResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *RedeemCodeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RedeemCodeResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetRedeemCodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*RedeemCodeResponse  `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedeemCodeListResponse) Reset() {
	*x = GetRedeemCodeListResponse{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedeemCodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedeemCodeListResponse) ProtoMessage() {}

func (x *GetRedeemCodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedeemCodeListResponse.ProtoReflect.Descriptor instead.
func (*GetRedeemCodeListResponse) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{7}
}

func (x *GetRedeemCodeListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRedeemCodeListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRedeemCodeListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRedeemCodeListResponse) GetData() []*RedeemCodeResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRedeemCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ExpirationAt  string                 `protobuf:"bytes,3,opt,name=expiration_at,json=expirationAt,proto3" json:"expiration_at,omitempty"`
	IsDel         int32                  `protobuf:"varint,4,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRedeemCodeRequest) Reset() {
	*x = UpdateRedeemCodeRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRedeemCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRedeemCodeRequest) ProtoMessage() {}

func (x *UpdateRedeemCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRedeemCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateRedeemCodeRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRedeemCodeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRedeemCodeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRedeemCodeRequest) GetExpirationAt() string {
	if x != nil {
		return x.ExpirationAt
	}
	return ""
}

func (x *UpdateRedeemCodeRequest) GetIsDel() int32 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

type UseRedeemCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedeemCodeId  int64                  `protobuf:"varint,1,opt,name=redeem_code_id,json=redeemCodeId,proto3" json:"redeem_code_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseRedeemCodeRequest) Reset() {
	*x = UseRedeemCodeRequest{}
	mi := &file_redeem_code_redeem_code_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseRedeemCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseRedeemCodeRequest) ProtoMessage() {}

func (x *UseRedeemCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redeem_code_redeem_code_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseRedeemCodeRequest.ProtoReflect.Descriptor instead.
func (*UseRedeemCodeRequest) Descriptor() ([]byte, []int) {
	return file_redeem_code_redeem_code_proto_rawDescGZIP(), []int{9}
}

func (x *UseRedeemCodeRequest) GetRedeemCodeId() int64 {
	if x != nil {
		return x.RedeemCodeId
	}
	return 0
}

func (x *UseRedeemCodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_redeem_code_redeem_code_proto protoreflect.FileDescriptor

const file_redeem_code_redeem_code_proto_rawDesc = "" +
	"\n" +
	"\x1dredeem_code/redeem_code.proto\x12\vredeem_code\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x02\n" +
	"\x1cCreateRedeemCodeBatchRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vusage_limit\x18\x03 \x01(\x05R\n" +
	"usageLimit\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x06 \x01(\tR\aendedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"creator_id\x18\b \x01(\x03R\tcreatorId\x12!\n" +
	"\fcreator_name\x18\t \x01(\tR\vcreatorName\"\x84\x04\n" +
	"\x17RedeemCodeBatchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vusage_limit\x18\x04 \x01(\x05R\n" +
	"usageLimit\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"used_count\x18\x06 \x01(\x05R\tusedCount\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"creator_id\x18\n" +
	" \x01(\x03R\tcreatorId\x12!\n" +
	"\fcreator_name\x18\v \x01(\tR\vcreatorName\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x0eGetListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa1\x01\n" +
	"\x1eGetRedeemCodeBatchListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x128\n" +
	"\x04data\x18\x04 \x03(\v2$.redeem_code.RedeemCodeBatchResponseR\x04data\"\xb8\x01\n" +
	"\x1cUpdateRedeemCodeBatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\xca\x03\n" +
	"\x12RedeemCodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x14redeem_code_batch_id\x18\x02 \x01(\x03R\x11redeemCodeBatchId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1f\n" +
	"\vusage_limit\x18\x05 \x01(\x05R\n" +
	"usageLimit\x12\x1d\n" +
	"\n" +
	"used_count\x18\x06 \x01(\x05R\tusedCount\x12?\n" +
	"\rexpiration_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fexpirationAt\x12\x15\n" +
	"\x06is_del\x18\b \x01(\x05R\x05isDel\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x97\x01\n" +
	"\x19GetRedeemCodeListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x123\n" +
	"\x04data\x18\x04 \x03(\v2\x1f.redeem_code.RedeemCodeResponseR\x04data\"{\n" +
	"\x17UpdateRedeemCodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rexpiration_at\x18\x03 \x01(\tR\fexpirationAt\x12\x15\n" +
	"\x06is_del\x18\x04 \x01(\x05R\x05isDel\"U\n" +
	"\x14UseRedeemCodeRequest\x12$\n" +
	"\x0eredeem_code_id\x18\x01 \x01(\x03R\fredeemCodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xf3\x06\n" +
	"\n" +
	"RedeemCode\x12j\n" +
	"\x15CreateRedeemCodeBatch\x12).redeem_code.CreateRedeemCodeBatchRequest\x1a$.redeem_code.RedeemCodeBatchResponse\"\x00\x12W\n" +
	"\x15RedeemCodeBatchDetail\x12\x16.redeem_code.IDRequest\x1a$.redeem_code.RedeemCodeBatchResponse\"\x00\x12d\n" +
	"\x16GetRedeemCodeBatchList\x12\x1b.redeem_code.GetListRequest\x1a+.redeem_code.GetRedeemCodeBatchListResponse\"\x00\x12\\\n" +
	"\x15UpdateRedeemCodeBatch\x12).redeem_code.UpdateRedeemCodeBatchRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x15DeleteRedeemCodeBatch\x12\x16.redeem_code.IDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x10RedeemCodeDetail\x12\x16.redeem_code.IDRequest\x1a\x1f.redeem_code.RedeemCodeResponse\"\x00\x12Z\n" +
	"\x11GetRedeemCodeList\x12\x1b.redeem_code.GetListRequest\x1a&.redeem_code.GetRedeemCodeListResponse\"\x00\x12R\n" +
	"\x10UpdateRedeemCode\x12$.redeem_code.UpdateRedeemCodeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x10DeleteRedeemCode\x12\x16.redeem_code.IDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\rUseRedeemCode\x12!.redeem_code.UseRedeemCodeRequest\x1a\x16.google.protobuf.Empty\"\x00BUZSgithub.com/1348453525/user-redeem-code-grpc/redeem-code-srv/proto/redeem_code;protob\x06proto3"

var (
	file_redeem_code_redeem_code_proto_rawDescOnce sync.Once
	file_redeem_code_redeem_code_proto_rawDescData []byte
)

func file_redeem_code_redeem_code_proto_rawDescGZIP() []byte {
	file_redeem_code_redeem_code_proto_rawDescOnce.Do(func() {
		file_redeem_code_redeem_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redeem_code_redeem_code_proto_rawDesc), len(file_redeem_code_redeem_code_proto_rawDesc)))
	})
	return file_redeem_code_redeem_code_proto_rawDescData
}

var file_redeem_code_redeem_code_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_redeem_code_redeem_code_proto_goTypes = []any{
	(*CreateRedeemCodeBatchRequest)(nil),   // 0: redeem_code.CreateRedeemCodeBatchRequest
	(*RedeemCodeBatchResponse)(nil),        // 1: redeem_code.RedeemCodeBatchResponse
	(*IDRequest)(nil),                      // 2: redeem_code.IDRequest
	(*GetListRequest)(nil),                 // 3: redeem_code.GetListRequest
	(*GetRedeemCodeBatchListResponse)(nil), // 4: redeem_code.GetRedeemCodeBatchListResponse
	(*UpdateRedeemCodeBatchRequest)(nil),   // 5: redeem_code.UpdateRedeemCodeBatchRequest
	(*RedeemCodeResponse)(nil),             // 6: redeem_code.RedeemCodeResponse
	(*GetRedeemCodeListResponse)(nil),      // 7: redeem_code.GetRedeemCodeListResponse
	(*UpdateRedeemCodeRequest)(nil),        // 8: redeem_code.UpdateRedeemCodeRequest
	(*UseRedeemCodeRequest)(nil),           // 9: redeem_code.UseRedeemCodeRequest
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 11: google.protobuf.Empty
}
var file_redeem_code_redeem_code_proto_depIdxs = []int32{
	10, // 0: redeem_code.RedeemCodeBatchResponse.started_at:type_name -> google.protobuf.Timestamp
	10, // 1: redeem_code.RedeemCodeBatchResponse.ended_at:type_name -> google.protobuf.Timestamp
	10, // 2: redeem_code.RedeemCodeBatchResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: redeem_code.RedeemCodeBatchResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: redeem_code.GetRedeemCodeBatchListResponse.data:type_name -> redeem_code.RedeemCodeBatchResponse
	10, // 5: redeem_code.RedeemCodeResponse.expiration_at:type_name -> google.protobuf.Timestamp
	10, // 6: redeem_code.RedeemCodeResponse.deleted_at:type_name -> google.protobuf.Timestamp
	10, // 7: redeem_code.RedeemCodeResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 8: redeem_code.RedeemCodeResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: redeem_code.GetRedeemCodeListResponse.data:type_name -> redeem_code.RedeemCodeResponse
	0,  // 10: redeem_code.RedeemCode.CreateRedeemCodeBatch:input_type -> redeem_code.CreateRedeemCodeBatchRequest
	2,  // 11: redeem_code.RedeemCode.RedeemCodeBatchDetail:input_type -> redeem_code.IDRequest
	3,  // 12: redeem_code.RedeemCode.GetRedeemCodeBatchList:input_type -> redeem_code.GetListRequest
	5,  // 13: redeem_code.RedeemCode.UpdateRedeemCodeBatch:input_type -> redeem_code.UpdateRedeemCodeBatchRequest
	2,  // 14: redeem_code.RedeemCode.DeleteRedeemCodeBatch:input_type -> redeem_code.IDRequest
	2,  // 15: redeem_code.RedeemCode.RedeemCodeDetail:input_type -> redeem_code.IDRequest
	3,  // 16: redeem_code.RedeemCode.GetRedeemCodeList:input_type -> redeem_code.GetListRequest
	8,  // 17: redeem_code.RedeemCode.UpdateRedeemCode:input_type -> redeem_code.UpdateRedeemCodeRequest
	2,  // 18: redeem_code.RedeemCode.DeleteRedeemCode:input_type -> redeem_code.IDRequest
	9,  // 19: redeem_code.RedeemCode.UseRedeemCode:input_type -> redeem_code.UseRedeemCodeRequest
	1,  // 20: redeem_code.RedeemCode.CreateRedeemCodeBatch:output_type -> redeem_code.RedeemCodeBatchResponse
	1,  // 21: redeem_code.RedeemCode.RedeemCodeBatchDetail:output_type -> redeem_code.RedeemCodeBatchResponse
	4,  // 22: redeem_code.RedeemCode.GetRedeemCodeBatchList:output_type -> redeem_code.GetRedeemCodeBatchListResponse
	11, // 23: redeem_code.RedeemCode.UpdateRedeemCodeBatch:output_type -> google.protobuf.Empty
	11, // 24: redeem_code.RedeemCode.DeleteRedeemCodeBatch:output_type -> google.protobuf.Empty
	6,  // 25: redeem_code.RedeemCode.RedeemCodeDetail:output_type -> redeem_code.RedeemCodeResponse
	7,  // 26: redeem_code.RedeemCode.GetRedeemCodeList:output_type -> redeem_code.GetRedeemCodeListResponse
	11, // 27: redeem_code.RedeemCode.UpdateRedeemCode:output_type -> google.protobuf.Empty
	11, // 28: redeem_code.RedeemCode.DeleteRedeemCode:output_type -> google.protobuf.Empty
	11, // 29: redeem_code.RedeemCode.UseRedeemCode:output_type -> google.protobuf.Empty
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_redeem_code_redeem_code_proto_init() }
func file_redeem_code_redeem_code_proto_init() {
	if File_redeem_code_redeem_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redeem_code_redeem_code_proto_rawDesc), len(file_redeem_code_redeem_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redeem_code_redeem_code_proto_goTypes,
		DependencyIndexes: file_redeem_code_redeem_code_proto_depIdxs,
		MessageInfos:      file_redeem_code_redeem_code_proto_msgTypes,
	}.Build()
	File_redeem_code_redeem_code_proto = out.File
	file_redeem_code_redeem_code_proto_goTypes = nil
	file_redeem_code_redeem_code_proto_depIdxs = nil
}
