// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: redeem_code/redeem_code.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedeemCode_CreateRedeemCodeBatch_FullMethodName  = "/redeem_code.RedeemCode/CreateRedeemCodeBatch"
	RedeemCode_RedeemCodeBatchDetail_FullMethodName  = "/redeem_code.RedeemCode/RedeemCodeBatchDetail"
	RedeemCode_GetRedeemCodeBatchList_FullMethodName = "/redeem_code.RedeemCode/GetRedeemCodeBatchList"
	RedeemCode_UpdateRedeemCodeBatch_FullMethodName  = "/redeem_code.RedeemCode/UpdateRedeemCodeBatch"
	RedeemCode_DeleteRedeemCodeBatch_FullMethodName  = "/redeem_code.RedeemCode/DeleteRedeemCodeBatch"
	RedeemCode_RedeemCodeDetail_FullMethodName       = "/redeem_code.RedeemCode/RedeemCodeDetail"
	RedeemCode_GetRedeemCodeList_FullMethodName      = "/redeem_code.RedeemCode/GetRedeemCodeList"
	RedeemCode_UpdateRedeemCode_FullMethodName       = "/redeem_code.RedeemCode/UpdateRedeemCode"
	RedeemCode_DeleteRedeemCode_FullMethodName       = "/redeem_code.RedeemCode/DeleteRedeemCode"
	RedeemCode_UseRedeemCode_FullMethodName          = "/redeem_code.RedeemCode/UseRedeemCode"
)

// RedeemCodeClient is the client API for RedeemCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RedeemCode 服务
type RedeemCodeClient interface {
	// 创建兑换码批次
	CreateRedeemCodeBatch(ctx context.Context, in *CreateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error)
	// 获取兑换码批次详情
	RedeemCodeBatchDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error)
	// 获取兑换码批次列表
	GetRedeemCodeBatchList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeBatchListResponse, error)
	// 更新兑换码批次
	UpdateRedeemCodeBatch(ctx context.Context, in *UpdateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除兑换码批次
	DeleteRedeemCodeBatch(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取兑换码详情
	RedeemCodeDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeResponse, error)
	// 获取兑换码列表
	GetRedeemCodeList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeListResponse, error)
	// 更新兑换码
	UpdateRedeemCode(ctx context.Context, in *UpdateRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除兑换码
	DeleteRedeemCode(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 使用兑换码
	UseRedeemCode(ctx context.Context, in *UseRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type redeemCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRedeemCodeClient(cc grpc.ClientConnInterface) RedeemCodeClient {
	return &redeemCodeClient{cc}
}

func (c *redeemCodeClient) CreateRedeemCodeBatch(ctx context.Context, in *CreateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCodeBatchResponse)
	err := c.cc.Invoke(ctx, RedeemCode_CreateRedeemCodeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) RedeemCodeBatchDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCodeBatchResponse)
	err := c.cc.Invoke(ctx, RedeemCode_RedeemCodeBatchDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) GetRedeemCodeBatchList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeBatchListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedeemCodeBatchListResponse)
	err := c.cc.Invoke(ctx, RedeemCode_GetRedeemCodeBatchList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) UpdateRedeemCodeBatch(ctx context.Context, in *UpdateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RedeemCode_UpdateRedeemCodeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) DeleteRedeemCodeBatch(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RedeemCode_DeleteRedeemCodeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) RedeemCodeDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCodeResponse)
	err := c.cc.Invoke(ctx, RedeemCode_RedeemCodeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) GetRedeemCodeList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedeemCodeListResponse)
	err := c.cc.Invoke(ctx, RedeemCode_GetRedeemCodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) UpdateRedeemCode(ctx context.Context, in *UpdateRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RedeemCode_UpdateRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) DeleteRedeemCode(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RedeemCode_DeleteRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemCodeClient) UseRedeemCode(ctx context.Context, in *UseRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RedeemCode_UseRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedeemCodeServer is the server API for RedeemCode service.
// All implementations must embed UnimplementedRedeemCodeServer
// for forward compatibility.
//
// RedeemCode 服务
type RedeemCodeServer interface {
	// 创建兑换码批次
	CreateRedeemCodeBatch(context.Context, *CreateRedeemCodeBatchRequest) (*RedeemCodeBatchResponse, error)
	// 获取兑换码批次详情
	RedeemCodeBatchDetail(context.Context, *IDRequest) (*RedeemCodeBatchResponse, error)
	// 获取兑换码批次列表
	GetRedeemCodeBatchList(context.Context, *GetListRequest) (*GetRedeemCodeBatchListResponse, error)
	// 更新兑换码批次
	UpdateRedeemCodeBatch(context.Context, *UpdateRedeemCodeBatchRequest) (*emptypb.Empty, error)
	// 删除兑换码批次
	DeleteRedeemCodeBatch(context.Context, *IDRequest) (*emptypb.Empty, error)
	// 获取兑换码详情
	RedeemCodeDetail(context.Context, *IDRequest) (*RedeemCodeResponse, error)
	// 获取兑换码列表
	GetRedeemCodeList(context.Context, *GetListRequest) (*GetRedeemCodeListResponse, error)
	// 更新兑换码
	UpdateRedeemCode(context.Context, *UpdateRedeemCodeRequest) (*emptypb.Empty, error)
	// 删除兑换码
	DeleteRedeemCode(context.Context, *IDRequest) (*emptypb.Empty, error)
	// 使用兑换码
	UseRedeemCode(context.Context, *UseRedeemCodeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRedeemCodeServer()
}

// UnimplementedRedeemCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedeemCodeServer struct{}

func (UnimplementedRedeemCodeServer) CreateRedeemCodeBatch(context.Context, *CreateRedeemCodeBatchRequest) (*RedeemCodeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRedeemCodeBatch not implemented")
}
func (UnimplementedRedeemCodeServer) RedeemCodeBatchDetail(context.Context, *IDRequest) (*RedeemCodeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemCodeBatchDetail not implemented")
}
func (UnimplementedRedeemCodeServer) GetRedeemCodeBatchList(context.Context, *GetListRequest) (*GetRedeemCodeBatchListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedeemCodeBatchList not implemented")
}
func (UnimplementedRedeemCodeServer) UpdateRedeemCodeBatch(context.Context, *UpdateRedeemCodeBatchRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRedeemCodeBatch not implemented")
}
func (UnimplementedRedeemCodeServer) DeleteRedeemCodeBatch(context.Context, *IDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRedeemCodeBatch not implemented")
}
func (UnimplementedRedeemCodeServer) RedeemCodeDetail(context.Context, *IDRequest) (*RedeemCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemCodeDetail not implemented")
}
func (UnimplementedRedeemCodeServer) GetRedeemCodeList(context.Context, *GetListRequest) (*GetRedeemCodeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedeemCodeList not implemented")
}
func (UnimplementedRedeemCodeServer) UpdateRedeemCode(context.Context, *UpdateRedeemCodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRedeemCode not implemented")
}
func (UnimplementedRedeemCodeServer) DeleteRedeemCode(context.Context, *IDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRedeemCode not implemented")
}
func (UnimplementedRedeemCodeServer) UseRedeemCode(context.Context, *UseRedeemCodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UseRedeemCode not implemented")
}
func (UnimplementedRedeemCodeServer) mustEmbedUnimplementedRedeemCodeServer() {}
func (UnimplementedRedeemCodeServer) testEmbeddedByValue()                    {}

// UnsafeRedeemCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedeemCodeServer will
// result in compilation errors.
type UnsafeRedeemCodeServer interface {
	mustEmbedUnimplementedRedeemCodeServer()
}

func RegisterRedeemCodeServer(s grpc.ServiceRegistrar, srv RedeemCodeServer) {
	// If the following call panics, it indicates UnimplementedRedeemCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedeemCode_ServiceDesc, srv)
}

func _RedeemCode_CreateRedeemCodeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRedeemCodeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).CreateRedeemCodeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_CreateRedeemCodeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).CreateRedeemCodeBatch(ctx, req.(*CreateRedeemCodeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_RedeemCodeBatchDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).RedeemCodeBatchDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_RedeemCodeBatchDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).RedeemCodeBatchDetail(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_GetRedeemCodeBatchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).GetRedeemCodeBatchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_GetRedeemCodeBatchList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).GetRedeemCodeBatchList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_UpdateRedeemCodeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRedeemCodeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).UpdateRedeemCodeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_UpdateRedeemCodeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).UpdateRedeemCodeBatch(ctx, req.(*UpdateRedeemCodeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_DeleteRedeemCodeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).DeleteRedeemCodeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_DeleteRedeemCodeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).DeleteRedeemCodeBatch(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_RedeemCodeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).RedeemCodeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_RedeemCodeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).RedeemCodeDetail(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_GetRedeemCodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).GetRedeemCodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_GetRedeemCodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).GetRedeemCodeList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_UpdateRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).UpdateRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_UpdateRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).UpdateRedeemCode(ctx, req.(*UpdateRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_DeleteRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).DeleteRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_DeleteRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).DeleteRedeemCode(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemCode_UseRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemCodeServer).UseRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedeemCode_UseRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemCodeServer).UseRedeemCode(ctx, req.(*UseRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedeemCode_ServiceDesc is the grpc.ServiceDesc for RedeemCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedeemCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redeem_code.RedeemCode",
	HandlerType: (*RedeemCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRedeemCodeBatch",
			Handler:    _RedeemCode_CreateRedeemCodeBatch_Handler,
		},
		{
			MethodName: "RedeemCodeBatchDetail",
			Handler:    _RedeemCode_RedeemCodeBatchDetail_Handler,
		},
		{
			MethodName: "GetRedeemCodeBatchList",
			Handler:    _RedeemCode_GetRedeemCodeBatchList_Handler,
		},
		{
			MethodName: "UpdateRedeemCodeBatch",
			Handler:    _RedeemCode_UpdateRedeemCodeBatch_Handler,
		},
		{
			MethodName: "DeleteRedeemCodeBatch",
			Handler:    _RedeemCode_DeleteRedeemCodeBatch_Handler,
		},
		{
			MethodName: "RedeemCodeDetail",
			Handler:    _RedeemCode_RedeemCodeDetail_Handler,
		},
		{
			MethodName: "GetRedeemCodeList",
			Handler:    _RedeemCode_GetRedeemCodeList_Handler,
		},
		{
			MethodName: "UpdateRedeemCode",
			Handler:    _RedeemCode_UpdateRedeemCode_Handler,
		},
		{
			MethodName: "DeleteRedeemCode",
			Handler:    _RedeemCode_DeleteRedeemCode_Handler,
		},
		{
			MethodName: "UseRedeemCode",
			Handler:    _RedeemCode_UseRedeemCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redeem_code/redeem_code.proto",
}
